parameters:
    itkg_reference.transformer.reference.class : Itkg\ReferenceApiBundle\Transformer\ReferenceTransformer
    itkg_reference.transformer.reference_type_collection.class : Itkg\ReferenceApiBundle\Transformer\ReferenceTypeCollectionTransformer
    itkg_reference.transformer.reference_type.class : Itkg\ReferenceApiBundle\Transformer\ReferenceTypeTransformer
    itkg_reference.transformer.reference_collection.class : Itkg\ReferenceApiBundle\Transformer\ReferenceCollectionTransformer

services:

## TRANSFORMERS ##

    itkg_reference.transformer.reference:
        class:            %itkg_reference.transformer.reference.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    itkg_reference.transformer.reference_type_collection:
        class: %itkg_reference.transformer.reference_type_collection.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    itkg_reference.transformer.reference_type:
        class: %itkg_reference.transformer.reference_type.class%
        arguments:
            - @open_orchestra_backoffice.manager.translation_choice
        tags:
            - { name: open_orchestra_api.transformer.strategy}

    itkg_reference.transformer.reference_collection:
        class: %itkg_reference.transformer.reference_collection.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
