parameters:
    itkg_reference.navigation_panel.reference_types.parameters:
        -
          name: reference_type_id
          title: itkg_reference_bundle.form.reference_type.id
          visible: true
          activateColvis: true
          searchField: text
        -
          name: name
          title: itkg_reference_bundle.form.reference_type.name
          visible: true
          activateColvis: true
          searchField: text


    itkg_reference.navigation_panel.reference_type.parameters:
        -
          name: name
          title: open_orchestra_backoffice.table.content_type.name
          activateColvis: true
          searchField: text
