parameters:
    itkg_reference_bundle.type.itkg_reference.class : Itkg\ReferenceBundle\Form\Type\ReferenceTypeType

services:
    # Reference Type Form Builder
    itkg_reference_bundle.type.itkg_reference:
        class: %itkg_reference_bundle.type.itkg_reference.class%
        arguments:
            - %itkg_reference.document.reference_type.class%
            - @translator
            - @open_orchestra_backoffice.listener.translate_value_initializer
        tags:
            - {name: form.type, alias: itkg_reference_type}
