parameters:
    itkg_reference.role:
        role_access_reference:
            category: open_orchestra_backoffice.left_menu.editorial.title
            label: open_orchestra_role.label_access_reference
        role_access_reference_type:
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_reference_type
