parameters:
    itkg_reference.role:
        role_access_reference_type :
            category: open_orchestra_backoffice.left_menu.editorial.title
            label: open_orchestra_role.label_access_reference_type
        role_access_reference_type_for_reference :
            category: open_orchestra_backoffice.left_menu.administration.title
            label: open_orchestra_role.label_access_for_reference
