parameters:
    itkg_reference.repository.reference.class : Itkg\ReferenceBundle\Repository\ReferenceRepository
    itkg_reference.repository.reference_type.class : Itkg\ReferenceBundle\Repository\ReferenceTypeRepository

    itkg_reference.document.reference_type.class : Itkg\ReferenceBundle\Document\ReferenceType
    itkg_reference.document.reference.class : Itkg\ReferenceBundle\Document\Reference

    itkg_reference.left_panel.reference_types.class : Itkg\ReferenceBundle\LeftPanel\Strategies\ReferenceTypePanelStrategy
    itkg_reference.left_panel.reference.class : Itkg\ReferenceBundle\LeftPanel\Strategies\ReferenceTypeForReferencePanelStrategy

    itkg_reference.manager.reference_type.class : Itkg\ReferenceBundle\Manager\ReferenceTypeManager
    itkg_reference.manager.reference.class : Itkg\ReferenceBundle\Manager\ReferenceManager

services:

## MODELS ##

    itkg_reference.repository.reference_type:
        class:            %itkg_reference.repository.reference_type.class%
        factory_service:  "doctrine.odm.mongodb.document_manager"
        factory_method:   "getRepository"
        arguments:
            - %itkg_reference.document.reference_type.class%

    itkg_reference.repository.reference:
        class:            %itkg_reference.repository.reference.class%
        factory_service:  "doctrine.odm.mongodb.document_manager"
        factory_method:   "getRepository"
        arguments:
            - %itkg_reference.document.reference.class%

## MENU STRATEGIES ##

    itkg_reference.left_panel.reference_types:
        class: %itkg_reference.left_panel.reference_types.class%
        arguments:
            - reference_types
            - ROLE_ACCESS_REFERENCE_TYPE
            - ItkgReferenceBundle
            - 12
        tags:
            - { name: open_orchestra_backoffice.left_panel.strategy }

    itkg_reference.left_panel.reference:
        class: %itkg_reference.left_panel.reference.class%
        arguments:
            - @itkg_reference.repository.reference_type
        tags:
            - { name: open_orchestra_backoffice.left_panel.strategy }

## MANAGER ##

    itkg_reference.manager.reference_type:
         class: %itkg_reference.manager.reference_type.class%

    itkg_reference.manager.reference:
         class: %itkg_reference.manager.reference.class%
         arguments:
            - @open_orchestra_backoffice.context_manager
