parameters:
    itkg_reference.navigation_panel.reference_types.class : Itkg\ReferenceBundle\NavigationPanel\Strategies\ReferenceTypePanelStrategy
    itkg_reference.navigation_panel.reference.class : Itkg\ReferenceBundle\NavigationPanel\Strategies\ReferenceTypeForReferencePanelStrategy

    itkg_reference.manager.reference_type.class : Itkg\ReferenceBundle\Manager\ReferenceTypeManager
    itkg_reference.manager.reference.class : Itkg\ReferenceBundle\Manager\ReferenceManager

services:

## MENU STRATEGIES ##

    itkg_reference.navigation_panel.reference_types:
        class: %itkg_reference.navigation_panel.reference_types.class%
        arguments:
            - reference_types
            - ROLE_ACCESS_REFERENCE_TYPE
            - 12
            - %open_orchestra_backoffice.navigation_panel.menu.administration%
            - %itkg_reference.navigation_panel.reference_types.parameters%
            - @translator
        tags:
            - { name: open_orchestra_backoffice.navigation_panel.strategy }

    itkg_reference.navigation_panel.reference:
        class: %itkg_reference.navigation_panel.reference.class%
        arguments:
            - @itkg_reference.repository.reference_type
            - %itkg_reference.navigation_panel.reference_type.parameters%
            - @open_orchestra_backoffice.manager.translation_choice
            - @translator
        tags:
            - { name: open_orchestra_backoffice.navigation_panel.strategy }

## MANAGER ##

    itkg_reference.manager.reference_type:
         class: %itkg_reference.manager.reference_type.class%

    itkg_reference.manager.reference:
         class: %itkg_reference.manager.reference.class%
         arguments:
            - @open_orchestra_backoffice.context_manager
