parameters:
    itkg_reference.repository.reference.class : Itkg\ReferenceBundle\Document\ReferenceRepository
    itkg_reference.document.reference.class : Itkg\ReferenceBundle\Document\Reference
    itkg_reference.transformer.reference.class : Itkg\ReferenceBundle\Transformer\ReferenceTransformer

services:
    itkg_reference.repository.reference:
        class:            %itkg_reference.repository.reference.class%
        factory_service:  "doctrine.odm.mongodb.document_manager"
        factory_method:   "getRepository"
        arguments:
            - %itkg_reference.document.reference.class%
        calls:
            - [ setCurrentSiteManager, [ @open_orchestra.manager.current_site ] ]

    itkg_reference.transformer.reference:
        class:            %itkg_reference.transformer.reference.class%
        tags:
            - { name: open_orchestra_api.transformer.strategy}
